FROM php:8.1-apache

# Instalamos dependencias del sistema
RUN apt-get update && apt-get install -y \
    libpng-dev libonig-dev libxml2-dev zip unzip git curl \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Instalamos Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Copiamos la app al contenedor
COPY . /var/www/html

# Activamos mod_rewrite
RUN a2enmod rewrite

# Cambiamos permisos y directorio
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html/storage

# Puerto expuesto
EXPOSE 80
